---
- name: Jenkins Installation
  hosts: new_machine
  vars:
    jenkins_url: http://127.0.0.1
    jenkins_port: 8080
    jenkins_install_via: "docker"
    jenkins_jobs: [
        "my-first-job",
      ]
  remote_user: azureuser
  tasks:
      - include_role:
           name: emmetog.jenkins

