---
- name: Get installed pip version
  become: yes
  become_method: sudo
  become_user: root
  command: pip --version
  register: pip_version_output
  ignore_errors: yes
  changed_when: false

- name: Download get-pip.py
  become: yes
  become_method: sudo
  become_user: root
  get_url: url=https://bootstrap.pypa.io/get-pip.py
           dest=/tmp/get-pip.py
  when: pip_version_output | failed or not pip_version_output.stdout | search(pip_version)

# Install pip if it's not already installed, or if
# the desired versions of pip aren't installed
# The regular expression extracts '9.0' out of '9.0.*'
- name: Install pip
  become: yes
  become_method: sudo
  become_user: root
  command: "python get-pip.py pip=={{ pip_version }}"
  when:  pip_version_output | failed or not pip_version_output.stdout | search(pip_version)
  args:
    chdir: /tmp
