- name: Ensure nexus directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /share/nexus

- name: Pull the latest official nexus docker image
  become: yes
  become_method: sudo
  become_user: root
  docker_image:  name=sonatype/nexus3:latest state=present force=yes
- name: Create a container from the nexus docker image
  become: yes
  become_method: sudo
  become_user: root
  docker_container:
    name: "nexus-server"
    image: "sonatype/nexus3"
    ports:
        - "8081:8081"
        
    volumes:
        - "/share/nexus:/var/nexus_home"
    state: present
    recreate: no
- name: Copy systemd service script to start and stop the nexus container
  become: yes
  become_method: sudo
  become_user: root
  copy: src=files/nexus.service dest=/etc/systemd/system
- name: Reload systemctl
  become: yes
  become_method: sudo
  become_user: root
  shell: systemctl reload-or-restart nexus
- name: Enable the docker-nexus service
  become: yes
  become_method: sudo
  become_user: root
  shell: systemctl enable nexus
