---

- name: Ensure jenkins home dir is created
  become: yes
  become_method: sudo
  become_user: root
  file:
    path: "{{ jenkins_home }}"
    mode: 0777
    owner: "{{ jenkins_config_owner }}"
    group: "{{ jenkins_config_group }}"
    state: directory
- name: Container is running (with ingress port)
  become: yes
  become_method: sudo
  become_user: root
  docker_container:
    name: "{{ jenkins_docker_container_name }}"
    image: "{{ jenkins_docker_image }}:latest"
    published_ports:
      - "{{ jenkins_port }}:8080"
    volumes:
      - "{{docker_path}}:/var/run/docker.sock"
      - "{{ jenkins_home }}:/var/jenkins_home"
    env:
      JAVA_OPTS: "{{ jenkins_java_opts }}"
  register: container_result
  when: jenkins_docker_expose_port


- name: Container is running (without ingress port)
  docker_container:
    name: "{{ jenkins_docker_container_name }}"
    image: "{{ jenkins_docker_image }}:{{ jenkins_version }}"
    expose: "8080"
    volumes:
      - "{{docker_path}}:/var/run/docker.sock "
      - "{{ jenkins_home }}:/var/jenkins_home"
    env:
      JAVA_OPTS: "{{ jenkins_java_opts }}"
  register: container_result
  when: not jenkins_docker_expose_port

- pause:
    seconds: 45
  when: container_result|changed
