---
- name: Add Docker Group
  become: yes
  become_method: sudo
  become_user: root
  group: name=docker state=present

- name: Add Docker Signing Key
  become: yes
  become_method: sudo
  become_user: root
  apt_key:
    keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present

- name: Add Docker Repo
  become: yes
  become_method: sudo
  become_user: root
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo debian-jessie main'
    filename: 'docker.list'

- name: Install Docker
  become: yes
  become_method: sudo
  become_user: root
  apt: name=docker-engine state=present

- name: Install docker-py
  become: yes
  become_method: sudo
  become_user: root
  pip: name=docker-py version=1.9.0
